#docker-compose.yml
services:
  n8n:
    build: .
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "5678:5678" # Expõe a porta 5678 do contêiner na porta 5678 do host
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME} # Se você for usar um domínio
      - N8N_PORT=5678
      - N8N_PROTOCOL=https # Mude para https se usar um proxy reverso com SSL
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/ # Se for usar um domínio
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE} # Defina seu fuso horário
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true 
      - N8N_RUNNERS_ENABLED=true 
      - N8N_EXPRESS_TRUST_PROX  
    volumes:
      - ${DATA_FOLDER}:/home/node/.n8n
      - /home/gracer2112/projetos/linkedin-automacao:/data/linkedin-automacao
    

